### ISSUE TITLE
lfs.dir crashing after first iteration on x64 bit windows 10

### ISSUE THREAD

**Issue by CapsAdmin** [spacewander/luafilesystem#6]
`.\luajit.exe -"e for path in require('lfs_ffi').dir('.') do print(path) end print('?')"`

**Comment by spacewander** [comment]
Maybe x64 bit Windows 10 uses a different version of `findnext`?
https://github.com/spacewander/luafilesystem/blob/master/lfs_ffi.lua#L288

As a backend programmer, I don't have the Windows environment to test it.

**Comment by sonoro1234** [comment]
@CapsAdmin 
Does it only happens in Windows10?

**Comment by CapsAdmin** [comment]
> @CapsAdmin
> Does it only happens in Windows10?

I only have access to windows xp in a virtual machine, but that fails with something else.

```lua
luajit: .\lfs_ffi.lua:255: cannot resolve symbol '_findfirst32': The specified procedure could not be found.

stack traceback:
        [C]: in function '__index'
        .\lfs_ffi.lua:255: in main chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x004020f0
```

**Comment by sonoro1234** [comment]
Could you try with https://github.com/sonoro1234/luafilesystem (unicode branch which is my default branch)

**Comment by sonoro1234** [comment]
you can switch unicode on/off with
lfs = require"lfs_ffi"
lfs.unicode = true|false
default is on

**Comment by spacewander** [comment]
@sonoro1234 
Maybe I should mention that people should use your fork in Windows.
For example, throw an error with your repo's URL when Windows is detected.
Since I don't a Windows environment to test/maintain the features.

**Comment by sonoro1234** [comment]
It is ok for me. 
I can test also linux now.

**Comment by spacewander** [comment]
@sonoro1234 
Done via https://github.com/spacewander/luafilesystem/commit/8ea5dda5460bd82d284fdbb0664a016cc7cde68b

**Comment by spacewander** [comment]
Don't support Windows anymore.

**Comment by sonoro1234** [comment]
Althought, ideal situation would be having only one lua file for all systems.
I am using lfs_ffi.lua in linux also but as yours and mine are getting different structure it is difficult to incorporate your changes into my repo!!!
