### ISSUE TITLE
dangling DIR pointer?

### ISSUE THREAD

**Issue by sonoro1234** [spacewander/luafilesystem#9]
Hi,

https://github.com/spacewander/luafilesystem/blob/master/lfs_ffi.lua#L207
is attaching a `DIR*` to a struct field but not to any table. I think that this does not prevent `__gc` to be called.

**Comment by spacewander** [comment]
Would you submit a fix for it? Thanks!

**Comment by sonoro1234** [comment]
> Would you submit a fix for it? Thanks!

Yes, I would solve it attaching `DIR*` to some anchor.
But first: Do you think I am right? Is it a dangling pointer?

**Comment by spacewander** [comment]
I think it is. Since GC doesn't traverse FFI struct.

**Comment by sonoro1234** [comment]
Just made PR #10

**Comment by sonoro1234** [comment]
On a later thought: We could be wrong (And nobody has reported an issue on that!!)
```Lua
dir_obj._dentry = dentry
```
dentry can be garbage collected but `dir_obj._dentry` will keep its value!!

I would be a different case if dentry was pointing to allocated memory (`dentry = ffi.new("int[25]")` for example)
